// Export all utility functions and classes
export * from './appUtils';
export * from './validation';
export * from './dateUtils';
export * from './locationUtils';
export * from './storageUtils';
export * from './networkUtils';

// Re-export commonly used utilities for convenience
export {
  initializeApp,
  requestPermissions,
  checkPermissions,
  formatFileSize,
  formatDuration,
  generateId,
  validateEmail,
  validatePassword,
  sanitizeFileName,
  getFileExtension,
  isImageFile,
  isDocumentFile,
  debounce,
  throttle,
  deepClone,
  capitalizeFirstLetter,
  truncateText,
  sleep,
  retry,
} from './appUtils';

export {
  validateProject,
  validateFieldData,
  validateMRVReport,
  validateCoordinates,
  validateMeasurement,
  validateFileUpload,
  validateRequired,
  validateMinLength,
  validateMaxLength,
  validateNumericRange,
} from './validation';

export {
  formatDate,
  formatDateTime,
  formatTime,
  getRelativeTime,
  isToday,
  isYesterday,
  isThisWeek,
  isThisMonth,
  isThisYear,
  addDays,
  addMonths,
  addYears,
  getStartOfDay,
  getEndOfDay,
  getStartOfWeek,
  getEndOfWeek,
  getStartOfMonth,
  getEndOfMonth,
  getDaysBetween,
  getMonthsBetween,
  getYearsBetween,
  parseDate,
  isValidDate,
  getCurrentTimestamp,
  getCurrentDate,
  getCurrentYear,
  getCurrentMonth,
  getCurrentDay,
  getWeekday,
  getMonthName,
  getQuarter,
  getDaysInMonth,
  isLeapYear,
} from './dateUtils';

export {
  requestLocationPermission,
  getCurrentLocation,
  watchLocation,
  stopWatchingLocation,
  calculateDistance,
  calculateBearing,
  formatDistance,
  formatBearing,
  isValidCoordinate,
  getLocationAccuracy,
  getLocationAccuracyColor,
  getLocationAccuracyIcon,
  getLocationErrorMessage,
  showLocationError,
  getLocationBounds,
  getLocationCenter,
  isLocationWithinBounds,
  getLocationHash,
  parseLocationHash,
} from './locationUtils';

export {
  storage,
  getFileSize,
  getFileInfo,
  createDirectory,
  deleteFile,
  copyFile,
  moveFile,
  readFile,
  writeFile,
  getDocumentDirectory,
  getCacheDirectory,
  getTempDirectory,
  getAppDataDirectory,
  getStorageInfo,
  cleanupTempFiles,
} from './storageUtils';

export {
  networkManager,
  isNetworkAvailable,
  isInternetAvailable,
  getConnectionType,
  waitForNetwork,
  waitForInternet,
  showNetworkError,
  showNetworkWarning,
  getNetworkQuality,
  getNetworkQualityColor,
  getNetworkQualityIcon,
  isSlowConnection,
  shouldUseLowQualityImages,
  shouldCompressImages,
  getOptimalImageQuality,
  getOptimalVideoQuality,
  getOptimalBatchSize,
  getOptimalRetryDelay,
  getOptimalTimeout,
  formatConnectionType,
  getNetworkStatusText,
  getNetworkStatusColor,
  getNetworkStatusIcon,
  isWifiConnection,
  isCellularConnection,
  isEthernetConnection,
  isBluetoothConnection,
  isVpnConnection,
  shouldWarnAboutDataUsage,
  getDataUsageWarning,
  shouldPauseLargeUploads,
  shouldResumeUploads,
} from './networkUtils';

