---
Organizations:
    - &OrdererOrg
        Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: crypto-config/ordererOrganizations/example.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"

    - &GovernmentOrg
        Name: GovernmentMSP
        ID: GovernmentMSP
        MSPDir: crypto-config/peerOrganizations/government.example.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('GovernmentMSP.admin', 'GovernmentMSP.peer', 'GovernmentMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('GovernmentMSP.admin', 'GovernmentMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('GovernmentMSP.admin')"
        AnchorPeers:
            - Host: peer0.government.example.com
              Port: 7051

    - &NGOOrg
        Name: NGOMSP
        ID: NGOMSP
        MSPDir: crypto-config/peerOrganizations/ngo.example.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('NGOMSP.admin', 'NGOMSP.peer', 'NGOMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('NGOMSP.admin', 'NGOMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('NGOMSP.admin')"
        AnchorPeers:
            - Host: peer0.ngo.example.com
              Port: 9051

    - &VerifierOrg
        Name: VerifierMSP
        ID: VerifierMSP
        MSPDir: crypto-config/peerOrganizations/verifier.example.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('VerifierMSP.admin', 'VerifierMSP.peer', 'VerifierMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('VerifierMSP.admin', 'VerifierMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('VerifierMSP.admin')"
        AnchorPeers:
            - Host: peer0.verifier.example.com
              Port: 11051

Capabilities:
    Channel: &ChannelCapabilities
        V2_0: true
    Orderer: &OrdererCapabilities
        V2_0: true
    Application: &ApplicationCapabilities
        V2_0: true

Application: &ApplicationDefaults
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        LifecycleEndorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
        Endorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
    Capabilities:
        <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
    OrdererType: etcdraft
    EtcdRaft:
        Consenters:
        - Host: orderer.example.com
          Port: 7050
          ClientTLSCert: crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt
          ServerTLSCert: crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities

Profiles:
    CarbonCreditsGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            CarbonCreditsConsortium:
                Organizations:
                    - *GovernmentOrg
                    - *NGOOrg
                    - *VerifierOrg

    CarbonCreditsChannel:
        Consortium: CarbonCreditsConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *GovernmentOrg
                - *NGOOrg
                - *VerifierOrg
            Capabilities:
                <<: *ApplicationCapabilities

